FROM pytorch/pytorch:latest

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update
RUN apt-get install gcc python-dev libpq-dev -y
# RUN apt-get install supervisor -y

COPY requirements.txt .
RUN pip install -r requirements.txt

# COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# CMD ["supervisord", "-n"]

COPY . .

ADD start-prod.sh /app

RUN chmod +x /app/start-prod.sh
