version: '3'
services:
    db:
        image: postgres
        container_name: fids_chatbot_db
        environment:
            - POSTGRES_DB=fids_chatbot_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    api:
        build: .
        command: ./start-reload.sh
        env_file: .env
        volumes:
            - .:/app
        ports:
            - '8000:8000'
        depends_on:
            - db
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '5050:80'
        depends_on:
            - db
